version: '3.8'

services:

  mariadb:
    image: mariadb:10.5.8
    container_name: partyhaan-mariadb
    volumes: 
      - ./mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=0C9TyX2S
      - MYSQL_DATABASE=partyhaandb
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=zQF2zLpn